### ISSUE TITLE
Github Flavored Markdown Blog

### ISSUE THREAD

**Issue by CertifiedRice** [CertifiedRice/certifiedrice-website#3]
Implementing Github Flavored markdown to the blog page using MDX.

**Comment by Olspe** [comment]
Hi,
Didn't know how else to contact you, but it looks like upon merging my light/dark  button code to your main, the portion of the code that deal with the hamburgur menu was deleted. I'm adding the deleted code here for your convince. On line 26 in components/Navbar.js, replace the line with the following:

<nav className="hamburger-menu">  {/* Olspe: Added classNames and html elements to make the burger icon */}
            <input id="menu__toggle" type="checkbox" />
            <label className="menu__btn" htmlFor="menu__toggle">
                <span className="myspan"></span>
            </label>
Hopefully that should fix it.

**Comment by CertifiedRice** [comment]
Hello, I don't quite see it in the code, searched it using the IDE search feature 
Any you could contact me through Discord `Certified Rice#8386` or through email
😄
